/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Cross-platform audio output device.
 *
 * Wraps [`volumecontrol::AudioDevice`] and exposes its API to Node.js.
 * All fallible methods return `napi::Result<T>`, which causes the JS side
 * to receive a thrown `Error` on failure.
 */
export declare class AudioDevice {
  /**
   * Returns the system default audio output device.
   *
   * # Errors
   *
   * Throws if the default device cannot be resolved.
   */
  static fromDefault(): AudioDevice
  /**
   * Returns the audio device identified by `id`.
   *
   * # Errors
   *
   * Throws if no device with the given identifier exists, or if the lookup
   * fails.
   */
  static fromId(id: string): AudioDevice
  /**
   * Returns the first audio device whose name contains `name`.
   *
   * The match is a case-insensitive substring search on most platforms.
   *
   * # Errors
   *
   * Throws if no matching device is found, or if the lookup fails.
   */
  static fromName(name: string): AudioDevice
  /**
   * Lists all available audio devices.
   *
   * # Errors
   *
   * Throws if the device list cannot be retrieved.
   */
  static list(): Array<DeviceInfo>
  /**
   * Returns the unique identifier for this device.
   *
   * The value is the same opaque string that [`list`](Self::list) yields as
   * `DeviceInfo.id` and that [`from_id`](Self::from_id) accepts as its
   * argument.  It is guaranteed to be non-empty.
   */
  get id(): string
  /**
   * Returns the human-readable display name of this device.
   *
   * The value is the same string that [`list`](Self::list) yields as
   * `DeviceInfo.name` and that [`from_name`](Self::from_name) uses for
   * substring matching.  It is guaranteed to be non-empty.
   */
  get name(): string
  /**
   * Returns the current volume level in the range `0..=100`.
   *
   * The value is returned as `u32` for JavaScript compatibility (napi-rs
   * does not support `u8` in `#[napi]` signatures).
   *
   * # Errors
   *
   * Throws if the volume cannot be read.
   */
  getVol(): number
  /**
   * Sets the volume level.
   *
   * `vol` is clamped to `0..=100` before being applied.  The parameter is
   * `u32` for JavaScript compatibility; values above `100` are clamped to
   * `100`.
   *
   * # Errors
   *
   * Throws if the volume cannot be set.
   */
  setVol(vol: number): void
  /**
   * Returns `true` if the device is currently muted.
   *
   * # Errors
   *
   * Throws if the mute state cannot be read.
   */
  isMute(): boolean
  /**
   * Mutes or unmutes the device.
   *
   * # Errors
   *
   * Throws if the mute state cannot be changed.
   */
  setMute(muted: boolean): void
  /**
   * Returns the device formatted as `"name (id)"`.
   *
   * Delegates to the [`fmt::Display`](std::fmt::Display) implementation of
   * the inner device.
   */
  toString(): string
}

/**
 * Plain data object representing an available audio device.
 *
 * Mirrors [`volumecontrol_core::DeviceInfo`].  Exposed to JS as a plain
 * object with `id` and `name` string properties.
 */
export interface DeviceInfo {
  /**
   * Platform-specific unique identifier for the device.
   *
   * Matches the value returned by [`AudioDevice::id`] and accepted by
   * [`AudioDevice::from_id`].
   */
  id: string
  /**
   * Human-readable display name for the device.
   *
   * Matches the value returned by [`AudioDevice::name`] and used for
   * substring matching by [`AudioDevice::from_name`].
   */
  name: string
}
