/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface DeviceInfo {
  /** Platform-specific unique identifier for the device. */
  id: string
  /** Human-readable display name for the device. */
  name: string
}
export declare class AudioDevice {
  /** Returns the system default audio output device. */
  static fromDefault(): AudioDevice
  /** Returns the audio device identified by `id`. */
  static fromId(id: string): AudioDevice
  /** Returns the first audio device whose name contains `name` (case-insensitive substring match). */
  static fromName(name: string): AudioDevice
  /** Lists all available audio output devices. */
  static list(): Array<DeviceInfo>
  /** Platform-specific unique identifier for this device. */
  get id(): string
  /** Human-readable display name for this device. */
  get name(): string
  /** Returns the current volume level in the range `0..=100`. */
  getVol(): number
  /** Sets the volume level. Values above 100 are clamped to 100. */
  setVol(vol: number): void
  /** Returns `true` if this device is currently muted. */
  isMute(): boolean
  /** Mutes or unmutes this device. */
  setMute(muted: boolean): void
  /** Returns the device formatted as `"name (id)"`. */
  toString(): string
}
